#!/usr/bin/env python3
"""Build targeted hard-case CSV from diagnose_errors JSONL.

Input JSONL rows are generated by diagnose_errors.py and contain:
  label, pred, category, source, ...

This script selects rows where label/pred contain configured confusion pairs
at the differing positions, with optional category filters and per-pair caps.
Output CSV format: plate,path
"""
from __future__ import annotations

import argparse
import csv
import json
import random
from collections import defaultdict
from pathlib import Path


def parse_pairs(raw: str) -> set[tuple[str, str]]:
    pairs: set[tuple[str, str]] = set()
    for item in (x.strip() for x in raw.split(",")):
        if not item:
            continue
        if ":" not in item:
            raise ValueError(f"invalid pair '{item}', expected A:B")
        a, b = (x.strip().upper() for x in item.split(":", 1))
        if len(a) != 1 or len(b) != 1:
            raise ValueError(f"invalid pair '{item}', expected single chars")
        pairs.add((a, b))
    if not pairs:
        raise ValueError("no valid confusion pairs provided")
    return pairs


def read_jsonl(path: Path) -> list[dict]:
    out: list[dict] = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            out.append(json.loads(line))
    return out


def row_confusions(label: str, pred: str) -> set[tuple[str, str]]:
    if not label or not pred or len(label) != len(pred):
        return set()
    diffs: set[tuple[str, str]] = set()
    for a, b in zip(label, pred):
        if a == b:
            continue
        diffs.add((a.upper(), b.upper()))
    return diffs


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--diag-jsonl", type=Path, required=True)
    ap.add_argument("--output", type=Path, required=True)
    ap.add_argument(
        "--pairs",
        default="D:0,0:D,F:E,E:F,B:8,8:B,S:5,5:S",
        help="comma-separated confusion pairs, e.g. D:0,0:D,F:E,E:F",
    )
    ap.add_argument(
        "--categories",
        default="char_1_2,len_mismatch",
        help="comma-separated categories from diagnose_errors.py",
    )
    ap.add_argument("--max-per-pair", type=int, default=1200)
    ap.add_argument("--max-total", type=int, default=8000)
    ap.add_argument("--seed", type=int, default=42)
    args = ap.parse_args()

    allowed_pairs = parse_pairs(args.pairs)
    allowed_cats = {x.strip() for x in args.categories.split(",") if x.strip()}
    rows = read_jsonl(args.diag_jsonl)
    rng = random.Random(args.seed)

    by_pair: dict[tuple[str, str], list[tuple[str, str]]] = defaultdict(list)
    for r in rows:
        cat = str(r.get("category") or "")
        if allowed_cats and cat not in allowed_cats:
            continue
        label = str(r.get("label") or "").strip()
        pred = str(r.get("pred") or "").strip()
        src = str(r.get("source") or "").strip()
        if not label or not src:
            continue
        diffs = row_confusions(label, pred)
        if not diffs:
            continue
        hit = sorted(diffs & allowed_pairs)
        if not hit:
            continue
        # Assign to first matched pair to keep sampling deterministic and simple.
        by_pair[hit[0]].append((label, src))

    selected: dict[str, str] = {}
    pair_stats: dict[str, int] = {}
    for pair in sorted(by_pair.keys()):
        items = by_pair[pair]
        rng.shuffle(items)
        take = items[: max(0, args.max_per_pair)]
        pair_stats[f"{pair[0]}->{pair[1]}"] = len(take)
        for label, src in take:
            selected[src] = label

    items = list(selected.items())
    rng.shuffle(items)
    if len(items) > args.max_total:
        items = items[: args.max_total]

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(["plate", "path"])
        for src, label in items:
            w.writerow([label, src])

    print(
        f"wrote {len(items)} rows -> {args.output} "
        f"(pairs={','.join(f'{k}:{v}' for k, v in sorted(pair_stats.items()))})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
